### ISSUE TITLE
options.livereload

### ISSUE THREAD

**Issue by topless** [gruntjs/grunt-contrib-watch#176]
As an example, instead of watching the sass files for changes which results in a refresh of the page every time we make a change, you should watch the css file that actually changes and can be injected in the page without a reload. I am proposing this from my own experience, that I was looking around for a couple of hours till figure out that I am watching the wrong type of files. An even better example would be to have multiwatch statement which monitors the less for example and livereloads on css change. 
Something like this ..

```
watch:
  build:
    options:
      base: BUILD_DIR
    files: ["#{SRC_DIR}/**/*.less"]
    tasks: ["build_css"]
  css:
    options:
      livereload: true
    files: "#{BUILD_CSS_DIR}/style.css"
```
