### ISSUE TITLE
Immediate exit without warning if a path doesn't exist

### ISSUE THREAD

**Issue by zakdances** [gruntjs/grunt-contrib-watch#183]
If have watch (v.0.5.1) configured like this

```
watch:
  sass:
    files: ['fakeDir/*.scss']
    tasks: ['sass:dev']
    options:
      nospawn: false
      livereload: false
```

And I try `grunt watch`, the terminal prints out

```
MyProject zak$ grunt watch
Running "watch:sass" (watch) task
Waiting...MyProject zak$
```

Why doesn't watch print a message like

```
"ERROR: 'fakeDir/' doesn't exist. Exiting..."
```

?
