### ISSUE TITLE
adding spawn: false option causes mocha tests to not run

### ISSUE THREAD

**Issue by jcollum-hcg** [gruntjs/grunt-contrib-watch#194]
Bug in Mocha-test? Watch? Not a bug? Well here's what happened: 

I've got a grunt task that runs correctly the first time (runs stylus, transpiles the coffee, runs the tests). But when the `watch` task kicks off it runs the `mochaTest:all` task but no tests get run.      

Config: 

```
    grunt.initConfig
        watch:
          coffee:
            files: ['app/assets/src/coffee/**/*.coffee', 'app/assets/src/coffee/*.coffee', 'app/webserver.coffee']
            tasks: ['coffee:dev', 'replace', 'mochaTest:all']
            options:
              nospawn: true
          test:
            files: ['test/calc/*.coffee', 'test/*.coffee']
            tasks: ['test']
            options:
              nospawn: true
          stylus:
            files: 'app/assets/src/styl/**/*.styl'
            tasks: 'stylus:dev'

        mochaTest:
          all:
            src: [ 'test/calc/*.coffee', 'test/*.coffee']
            options:
              reporter: 'nyan'
              timeout: 1000

     ...
     grunt.registerTask "test", [ "mochaTest"]
```

Running the test directly: 

```
    $ grunt 'mochaTest' 
    Running "mochaTest:all" (mochaTest) task
     ...   
    264 passing (10 seconds)
```

Ok, so that's working. But when the watch is triggered, no tests are run: 

```
    Waiting...
    OK
    >> File "test/dataLayer-test.coffee" changed.

    Running "mochaTest:all" (mochaTest) task

      0 passing (1 ms)
```

No tests got run. I must have something configured wrong. What's the problem here? Is it a bug? 

Versions: 

```
├─┬ grunt@0.4.1
├── grunt-contrib-coffee@0.7.0
├── grunt-contrib-stylus@0.5.0
├─┬ grunt-contrib-watch@0.5.3
├─┬ grunt-mocha-test@0.6.3
├── grunt-text-replace@0.3.2
```

Per Gilad's suggestion, no difference though: 

```
    grunt watch --verbose --debug
    ...

    Running "mochaTest:all" (mochaTest) task
    [D] Task source: /home/dev/projects/alpha/node_modules/grunt-mocha-test/tasks/mocha.js
    Verifying property mochaTest.all exists in config...OK
    Files: test/calc/calc-test.coffee, ...
      264 passing (9 seconds)
      5 pending

    >> File "test/ui-formulaEditor-test.coffee" changed.

    Running "mochaTest:all" (mochaTest) task
    [D] Task source: /home/dev/projects/alpha/node_modules/grunt-mocha-test/tasks/mocha.js
    Verifying property mochaTest.all exists in config...OK
    Files: test/calc/calc-test.coffee, ...
      0 passing (2 ms)
    ...
```

I changed `nospawn: false` to `spawn: true`. Didn't fix it. Removed `spawn: true` completely and suddenly the tests started running when files changed.
