### ISSUE TITLE
tasks is required, contradicting readme, weird performance behavior

### ISSUE THREAD

**Issue by bling** [gruntjs/grunt-contrib-watch#74]
the readme under section [Using the watch event](https://github.com/gruntjs/grunt-contrib-watch#using-the-watch-event) states an example where only the `files` property is specified.  however, when you do this, you will get an error `Required config property "watch.###.tasks" missing`.

i'm circumventing this by creating a `noop` task that does nothing, but i noticed something odd...

my config is as follows:

```
watch:
    coffee:
        tasks: ['noop']
        files: ['**/*.coffee', '!**/node_modules/**']
```

when i make a change to a coffeescript file, around 6 seconds later i'll get a `Running "noop" task, Done, without errors.`  this 6 seconds is also how long it takes for the initial scan of which files it needs to watch.  it looks like making a change to a file is forcing a rescan of all files.

i'm using v0.3.1.
